### ISSUE TITLE
Reserve VM

### ISSUE THREAD

**Issue by kc17** [demoyuw/k8s#1]
老師，您好：

這幾天比較忙碌，需要多一點時間使用VM，請老師幫忙延長，感謝！

姓名：kc
VM名稱：k8s-20180805-19、k8s-20180805-20

**Comment by demoyuw** [comment]
沒問題。k8s-20180805-19、k8s-20180805-20 這兩台VM延長使用ㄧ星期到 8/16 00:00。

**Comment by kc17** [comment]
老師，您好：

不好意思，請問 k8s-20180805-19、k8s-20180805-20 這2台 VM 是否已經關閉了呢？

最近處理公司一個重要的問題，才剛忙完一個段落，是否能再延長一點時間呢？

如果不行也沒關係的，實在是我自己時間不夠，謝謝老師！

BR,
KC

**Comment by demoyuw** [comment]
如我上面寫延長到 8/16 00:00。這兩台VM已經刪除了所以無法幫你恢復。你可以建立自己的虛擬機試試，如果使用上有問題也歡迎提問喔。

謝謝
