### ISSUE TITLE
kubectl get pods 延遲問題

### ISSUE THREAD

**Issue by MaxiuLiu** [demoyuw/k8s#16]
我在多 worker 的 k8s , 以 shutdown 指令關閉一個 worker, 然後以 get pods 指令觀察 pods 移轉狀況.
觀察到 get node 大約 30 秒會顯示該 worker  NotReady 
但是 get pods 需要大約五分鐘才會看到 pods 開始移轉到其他正常的 worker.

這種情況正常嗎?

我的 vm 是筆電上的虛擬機.

**Comment by demoyuw** [comment]
Hi maxiu,

是正常的，在infra層我們會幫軟體訂定一個時間，用來判斷節點是真的關機停止服務。還是單純VM進行重開機或者是網路異常造成的節點狀態Not ready。已k8s而言，這個時間大約在5~6分鐘。跟你環境是在筆電上無關。

**Comment by MaxiuLiu** [comment]
原來如此，謝謝。
