### ISSUE TITLE
在Debian上安裝docker-ce時遭遇問題求助

### ISSUE THREAD

**Issue by Darwinarch** [demoyuw/k8s#18]
依照 [docker debian官方安裝頁面](https://docs.docker.com/engine/install/debian/) 執行到
`$ sudo apt-get install docker-ce`時
發生以下錯誤: 
![2](https://user-images.githubusercontent.com/69334027/89771498-fa281500-db32-11ea-993f-4152e21385a6.jpg)
後來查了[Install Docker CE on Debian 10](https://www.linode.com/docs/applications/containers/how-to-install-docker-ce-on-debian-10/)這篇:
![6](https://user-images.githubusercontent.com/69334027/89771764-6c005e80-db33-11ea-8eb2-0335ba285c1c.jpg)
是 Docker 在 debian 上還未有可用的 stable 版本所造成 ! 
不過依據上面的建議將 stable 改為 edge、test、stretch ... 
並在執行  apt update 後, 還是得到一樣的結果 ... 
`E: Package 'docker-ce' has no installation candidate`
orz

我這邊的 debian版本如下:
`$  uname -a
Linux DevD01 4.19.0-10-686-pae #1 SMP Debian 4.19.132-1 (2020-07-24) i686 GNU/Linux`

**Comment by demoyuw** [comment]
Hi 我照著官方說明安裝，看起來沒遇到相同問題，下面

在gcp上申請debian 10 
![image](https://user-images.githubusercontent.com/6544941/89774346-488be280-db38-11ea-875a-07717f82f9fc.png)
![image](https://user-images.githubusercontent.com/6544941/89774584-c2bc6700-db38-11ea-8d1a-a2082fec7e86.png)
![image](https://user-images.githubusercontent.com/6544941/89774621-cf40bf80-db38-11ea-87cc-243cd4f75521.png)

** 連入後顯示usname -a，我注意到你的debian 是i686，是32位元的，我是x86_64 64位元**
![image](https://user-images.githubusercontent.com/6544941/89774386-5b061c00-db38-11ea-82ff-1eb0f8f1571d.png)

下面是照官方安裝步驟
![image](https://user-images.githubusercontent.com/6544941/89774662-e089cc00-db38-11ea-8825-603dcbd99061.png)
![image](https://user-images.githubusercontent.com/6544941/89774671-e41d5300-db38-11ea-85c9-b22d33352354.png)
![image](https://user-images.githubusercontent.com/6544941/89774676-e5e71680-db38-11ea-985a-30b459b36dd9.png)
![image](https://user-images.githubusercontent.com/6544941/89774681-e8497080-db38-11ea-8e79-fe15b971280d.png)
![image](https://user-images.githubusercontent.com/6544941/89774725-fb5c4080-db38-11ea-965f-e9b64adb6d2b.png)
![image](https://user-images.githubusercontent.com/6544941/89774734-0020f480-db39-11ea-9ec0-ce8815a1b36b.png)

查了一下，docker必須在64位元作業系統上運行。

**Comment by Darwinarch** [comment]
感謝demoyuw 大大回覆 
目前裝完 debian 64 位元後確實可以順利安裝 docker-ce  
![6](https://user-images.githubusercontent.com/69334027/89847581-f3db7c80-dbb6-11ea-9a86-3ebf7e2a98b0.jpg)
^^b
